<div class="doc small" style="">
    <h2 class="text-center">Assured Performance<br/>End User Agreement</h2>
    <p>
        <strong>
        BY CLICKING ON THE BUTTON MARKED "I ACCEPT" AT THE END OF THIS AGREEMENT AND/OR USING THE ASSURED PERFORMANCE WEBSITE OR SERVICES, YOU ACCEPT AND AGREE TO THE TERMS AND CONDITIONS OF THIS, THE ASSURED PERFORMANCE END USER AGREEMENT.  IF YOU DO NOT AGREE TO THE TERMS AND CONDITIONS OF ASSURED PERFORMACE AND THIS AGREEMENT, YOU MAY NOT ACCESS OR OTHERWISE USE THE ASSURED PERFORMANCE WEBSITE OR ANY ASSURED PERFORMANCE SERVICES.
        </strong>
    </p>
    <p>
        Assured Performance Network, Inc., a Minnesota corporation, (hereafter “ASSURED PERFORMANCE” or “we”) whose principal address is 24422 Avenida De La Carlota, Suite 490, Laguna Hills, CA 92653 provide(s) access to our website ("Site") which contains certain web-based software applications such as dataMANAGER, dataSAFE, dataIQ, and APEX, that when elected to participate in, facilitate communication, knowledge management, rebate transaction eligibility, performance reporting and benchmarking, and data analysis (collectively, the “Service”), subject to the terms of the following End User Agreement.
    </p>
    <p>
        <span class="underline">This Agreement.</span>  For purposes of this Agreement, the term "Agreement" means this Agreement, as well as all other terms, conditions, and rules that may be published or displayed from time to time by ASSURED PERFORMANCE on the Site or at any other link designated in this Agreement.  We may, in our sole discretion, change or modify any term or portion of this Agreement at any time without notice to you by posting such changes on the Site. Your continued use of the Site and the Service after we post such changes will constitute your agreement to the amended terms of this Agreement. This Agreement may not be otherwise amended except in writing signed by both parties.  YOU SHOULD READ THIS AGREEMENT EACH TIME YOU USE THE SERVICE.
    </p>
    <p>
        <span class="underline">"You".</span>  As used in this Agreement, "Member", "End User", or "you" shall refer to the person (including, but not limited to, a corporation, partnership, or individual) completing the registration process.  As used herein a "Member" is an entity or individual user that has privileges to use the Service, including any employer, employee, authorized third party or other independent contractor of a Member.
    </p>
    <p>
        ENTERING INTO THIS AGREEMENT ON BEHALF OF AN ENTITY (MULTI USER OPTION).  If you are entering into this Agreement on behalf of an entity, you represent and warrant to us (i) that you are 18 years old or older; (ii) that you are currently employed by or acting on behalf of the entity; (iii) that you have authority to enter into agreements and specifically this Agreement on behalf of the entity; (iv) that the entity agrees to be bound by the terms and conditions of this Agreement; and (v) that if the entity requires agreements to be entered into in any manner other than as suggested by this Agreement that you will promptly send to us written confirmation of such entity's acceptance of the terms set forth in this Agreement in the manner required by the entity.
    </p>
    <p>
        ENTERING INTO THIS AGREEMENT AS AN INDIVIDUAL OR SOLE PROPRIETOR (SINGLE USER OPTION).  If you are entering into this Agreement as an individual you represent (i) that you are an employee or authorized agent of an entity that has entered into this Agreement; (ii) you are 18 years old or older; (iii) that you agree to be bound to the terms and conditions of this Agreement; and (iv) that you will be able to perform your obligations under this Agreement.
    </p>
    <p>
        <span class="underline">The Service.</span> The Service is provided to business entities and their employees or authorized agents.  Any unauthorized commercial use of the Service, or unauthorized resale of its services, is expressly prohibited. You agree to abide by all applicable local, state, national and international laws and regulations and are solely responsible for all acts or omissions that occur under your account or password, including the content of your account as used through the Service. By way of example, and not as a limitation, you agree not to:
    </p>
    <ul>
        <li>Interfere with or disrupt networks connected to the Service or violate the regulations, policies or procedures of such networks;</li>
        <li>Attempt to gain unauthorized access to the Service, other accounts, computer systems or networks connected to the Service, through password mining or any other means;</li>
        <li>Place any software code (knowingly or unknowingly), on the Site or within the Service which may include, but not be limited to: cookies, bots, viruses, agents, sniffers or any and all other forms of user tracking processes, destructive processes or code, rerouting or jump functions, pop-up browser windows, or other forms of interference with the internal or external use of the Site or Service;</li>
        <li>Use the Site or Service on behalf of or for any entity, business or activity that is considered illegitimate or illegal or is willfully breaking any civil or criminal laws with its activities; or</li>
        <li>Interfere with another member's use and enjoyment of the Service or another entity's use and enjoyment of similar services.</li>
        <li>ASSURED PERFORMANCE reserves the right to reject your registration for any reason, at its sole discretion, and prohibit you from participating in the Service.  In addition, ASSURED PERFORMANCE reserves the right to terminate your use of the Service for any reason, at any time and from time to time, at its sole discretion.</li>
    </ul>
    <p>
        ASSURED PERFORMANCE reserves the right, for any reason, at its sole discretion, to terminate, change, suspend or discontinue any aspect of the Site or the Service, including, but not limited to, content, features or hours of availability.  ASSURED PERFORMANCE may also impose limits on certain features of the Service or restrict your access to part or all of the Site or the Service without notice or penalty.  Furthermore, you are entirely responsible for any and all activities that occur under your account.
    </p>
    <p>
        You agree to notify ASSURED PERFORMANCE immediately of any unauthorized use of your account or any other breach of security. You agree that ASSURED PERFORMANCE may implement certain automated procedures and software wizards for purposes of providing lost or forgotten passwords to you.  Such procedures and wizards will require you to have the appropriate identifying information.
    </p>
    <p>
        <span class="underline">Your Information.</span>  In the course of your use of the Service, you will provide certain information to ASSURED PERFORMANCE during the registration, postings or through e-mail features, etc., which may be personally identifiable to you, your employees and/or your customers (collectively the "End User Information").  You agree that (i) you are responsible for all End User Information, and ASSURED PERFORMANCE has no obligation to you for the accuracy or completeness of the End User Information; and (ii) you shall maintain and update End User Information as necessary to keep it current, complete and accurate.  Additionally, you acknowledge and agree that you are solely responsible for the ongoing accuracy and content of the End User Information that you have placed on the Site and within the Service.
    </p>
    <p>
        ASSURED PERFORMANCE will not edit, or disclose any personal information about you or your account, including its contents, without your prior written consent.  Such express written consent may be obtained by ASSURED PERFORMANCE from time to time in electronic form by using, without limitation, online agreements, software wizards or other acknowledgements on the Site.  Notwithstanding the foregoing, ASSURED PERFORMANCE may disclose information if ASSURED PERFORMANCE has a good faith belief that such action is necessary to: (1) conform to legal requirements or comply with legal process; (2) protect and defend the rights or property of ASSURED PERFORMANCE; (3) enforce this Agreement; or (4) act to protect the interests of its Members or others.  ASSURED PERFORMANCE does provide certain user information in aggregate form to third parties.
    </p>
    <p>
        You agree that ASSURED PERFORMANCE may access your account, including its contents, as stated above or to respond to service or technical issues. You further agree that ASSURED PERFORMANCE is not responsible or liable for the deletion or failure to store information.
    </p>
    <p>
        You grant to ASSURED PERFORMANCE the non-exclusive right to use your End User Information obtained under this Agreement for ASSURED PERFORMANCE's internal purposes and to share such information with other Members in order to perform the Services and as otherwise set forth in this Agreement.
    </p>
    <p>
        <span class="underline">Confidentiality.</span>  You will hold in confidence and, without the consent of the disclosing Member, will not use, reproduce, distribute, transmit, transfer, or disclose, directly or indirectly, in any form, by any means, or for any purpose, the disclosing Member's End User Information.  You may only disclose the disclosing Member's End User Information to Members who (i) have a need to know such information in connection with the Service; and (ii) are obligated by the this Agreement or otherwise in writing to not disclose the disclosing Member's End User Information.  Without limiting the foregoing, you will exercise at least the same standard of care in protecting the disclosing Member's End User Information as you do with your own End User Information, but in any event, no less than reasonable care.
    </p>
    <p>
        <span class="underline">DISCLAIMER OF WARRANTIES:</span> THE SITE AND SERVICE, INCLUDING ALL CONTENT, FUNCTIONS, MATERIALS AND INFORMATION MADE AVAILABLE ON OR ACCESSED THROUGH THE SITE OR THE SERVICE, ARE PROVIDED ON AN "AS IS", "AS AVAILABLE" BASIS WITHOUT REPRESENTATIONS OR WARRANTIES OF ANY KIND WHATSOEVER, EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION, NON-INFRINGEMENT, MERCHANTABILITY, ACCURACY OR FITNESS FOR A PARTICULAR PURPOSE.  ASSURED PERFORMANCE DOES NOT WARRANT THAT THE SERVICE OR THE FUNCTIONS, FEATURES OR CONTENT CONTAINED THEREIN OR IN THE SITE WILL BE TIMELY, SECURE, UNINTERRUPTED OR ERROR FREE, OR THAT DEFECTS WILL BE CORRECTED. IF YOU ARE DISSATISFIED WITH THE SITE, YOUR SOLE REMEDY IS TO DISCONTINUE USING THE SITE AND THE SERVICE. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF CERTAIN WARRANTIES, SO SOME OF THE ABOVE EXCLUSIONS MAY NOT APPLY TO CERTAIN MEMBERS IF DICTATED BY APPLICABLE LAW.
    </p>
    <p>
        <span class="underline">THIRD PARTY OFFERINGS.</span>  CERTAIN SERVICE OFFERINGS, FEATURES AND FUNCTIONS ARE PROVIDED TO YOU BY THIRD PARTIES, AFFILIATES, AND ALLIANCE PARTNERS. YOUR RIGHTS WITH RESPECT TO ANY THIRD PARTY PRODUCTS OR SERVICES SHALL BE AS SPECIFIED BY THE THIRD PARTY, NOT THIS AGREEMENT.  ASSURED PERFORMANCE MAKES NO REPRESENTATION OR WARRANTY WHATSOEVER WITH RESPECT TO THIRD PARTY PRODUCTS OR SERVICES, AND YOU AGREE TO HOLD ASSURED PERFORMANCE HARMLESS FOR ANY WARRANTIES OR REPRESENTATIONS THAT ARE PROVIDED BY ANY THIRD PARTY.
    </p>
    <p>
        LIMITATION OF LIABILITY: TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, UNDER NO CIRCUMSTANCES, INCLUDING, BUT NOT LIMITED TO, NEGLIGENCE, SHALL ASSURED PERFORMANCE BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL OR CONSEQUENTIAL DAMAGES THAT RESULT FROM THE USE OF OR THE INABILITY TO USE THE SERVICE, ANY CHANGES TO THE SERVICE, UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR TRANSMISSIONS OR DATA, ANY MATERIAL OR DATA SENT OR RECEIVED OR NOT SENT OR RECEIVED, OR ANY TRANSACTIONS ENTERED INTO THROUGH THE SERVICE. YOU SPECIFICALLY AGREE THAT ASSURED PERFORMANCE IS NOT RESPONSIBLE OR LIABLE FOR ANY THREATENING, DEFAMATORY, OBSCENE, OFFENSIVE OR ILLEGAL CONTENT OR CONDUCT OF ANY OTHER PARTY OR ANY INFRINGEMENT OF ANOTHER'S RIGHTS, INCLUDING INTELLECTUAL PROPERTY RIGHTS. IF YOU ARE DISSATISFIED WITH THE SERVICE, THE MATERIALS AVAILABLE ON OR THROUGH THE SERVICE, OR WITH ANY OF ASSURED PERFORMANCE'S TERMS AND CONDITIONS, YOUR SOLE AND EXCLUSIVE REMEDY IS TO DISCONTINUE USING THE SERVICE.
    </p>
    <p>
        SOME JURISDICTIONS DO NOT ALLOW THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES SO SOME OF THE ABOVE LIMITATIONS MAY NOT APPLY TO CERTAIN END USERS IF DICTATED BY APPLICABLE LAW. IF PERMITTED BY LAW, ASSURED PERFORMANCE'S LIABILITY IS LIMITED TO RESUPPLYING THE SERVICE; PROVIDED, HOWEVER THAT ASSURED PERFORMANCE SHALL NOT BE REQUIRED TO RESUPPLY ANY PRODUCTS OR SERVICES PROVIDED BY THIRD PARTIES.
    </p>
    <p>
        <span class="underline">Indemnification:</span>  You agree to indemnify, defend and hold ASSURED PERFORMANCE, its officers, directors, employees and agents (collectively, the "Indemnified Parties"), harmless from and against any and all claims, losses, damages, liabilities, judgments and fees and expenses related thereto (including, without limitation, reasonable attorneys' fees), incurred by an Indemnified Party in connection with any claims arising out of, based upon or resulting from any breach or violation by you of this Agreement or any use by you of the Service or the Site. ASSURED PERFORMANCE reserves the right, at its own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, and you shall not in any event settle or otherwise dispose of any matter without the prior written consent of ASSURED PERFORMANCE.
    </p>
    <p>
        <span class="underline">Termination:</span> ASSURED PERFORMANCE may terminate this Agreement and your account at any time, without notice, in ASSURED PERFORMANCE's sole discretion. If we breach this Agreement in any manner, your sole recourse and our sole liability is for you to immediately: (i) discontinue use of the Service; and/or (ii) notify ASSURED PERFORMANCE of termination of membership.
    </p>
    <p>
        In addition, ASSURED PERFORMANCE may terminate your account for inactivity, which is defined as failing to log into the Service for an extended period of time, as determined by ASSURED PERFORMANCE. The amount of time that ASSURED PERFORMANCE currently views as an "extended" period of time is a first log-on thirty (30) days or later after registration and after an initial log-on, one hundred eighty (180) days since your last log-on.  Upon termination of the Service, your right to use the Service immediately ceases. ASSURED PERFORMANCE shall have no obligation to maintain any content in your account.
    </p>
    <p><span class="underline">Advertisers:</span>  Any dealings with advertisers on the Service or participation in promotions, including the delivery of and the payment for goods and services, and any other terms, conditions, warranties or representations associated with such dealings or promotions, are solely between you and the advertiser or other third party. ASSURED PERFORMANCE shall not be responsible or liable for any part of any such dealings or promotions. In certain cases, ASSURED PERFORMANCE will be the billing party for such services and will be responsible for forwarding payment only. If a refund for services is provided by a third party, and ASSURED PERFORMANCE has forwarded payment to such third party, then the third party and not ASSURED PERFORMANCE will be responsible for any refund.  You agree not to contact ASSURED PERFORMANCE regarding such matters.</p>
    <p><span class="underline">Proprietary Rights</span> To Content: You acknowledge that content, including but not limited to text, software, music, sound, photographs, video, graphics or other material contained in either sponsor advertisements or email-distributed, commercially produced information presented to you by the Service, by ASSURED PERFORMANCE, or ASSURED PERFORMANCE's advertisers or other content providers, is protected by copyrights, trademarks, service marks, patents or other proprietary rights and laws. You may make a copy of this content for your personal, non-commercial use only, provided that you keep all copyright and other proprietary notices intact.  You may not modify, copy, reproduce, republish, upload, post, transmit, or distribute in any way content available through the Service, including code and software. You understand that ASSURED PERFORMANCE will pursue its rights under this Agreement and the law by any means legally available. You agree that ASSURED PERFORMANCE may access your computers and networks and any and all digital storage files in the event that ASSURED PERFORMANCE reasonably suspects you have violated its rights described in this paragraph.</p>
    <p><span class="underline">Choice of Law; Dispute Resolution:</span> This Agreement shall be governed by and in accordance with the laws of the State of California, in the United States of America without regard to conflicts of laws provisions. Except as provided below, all disputes or claims relating in any manner to this Agreement shall be settled by binding arbitration in accordance with the Commercial Arbitration Rules of the American Arbitration Association in Orange County, California.  The parties agree that the arbitrators in any such arbitration shall not be authorized to award any exemplary or punitive damages in connection with any claim settled by arbitration hereunder. The decision of the arbitrators shall be final and binding upon the parties and judgment upon the award may be entered in any court having competent jurisdiction.  Notwithstanding the foregoing, we shall have the right to apply to a court of competent jurisdiction for any appropriate temporary or permanent injunction or other equitable relief, in addition to other available remedies at law (e.g., damages).  You acknowledge that any use of the Site in violation of this Agreement shall constitute irreparable harm to us for which there is no remedy at law.  The parties agree that the exclusive venue for all actions and/or arbitrations relating in any manner to this Agreement shall only be in a court of competent jurisdiction or in arbitration, as the case may be, located in Orange County, California.  Each party consents and submits to the personal jurisdiction of such courts and irrevocably waives any and all defenses inconsistent with this Section.  The prevailing party in any dispute between the parties shall recover its reasonable attorneys' fees and costs from the non-prevailing party.</p>
    <p><span class="underline">Notices And Disclosures:</span> Except as explicitly stated otherwise, any notices shall be given by e-mail to, in the case of ASSURED PERFORMANCE, support@Assured Performance.net, or, in the case of an End User to either: (i) the e-mail address you provide to ASSURED PERFORMANCE during the registration process, (ii) the mailing address provided to ASSURED PERFORMANCE during the registration process by certified mail, postage prepaid and return receipt requested, or (iii) such other address as you may specify. Notice shall be deemed given twenty-four (24) hours after e-mail is sent, unless the sending party is notified that the e-mail address is invalid or, in the case of mailing, three (3) days after the date of mailing.</p>
    <p><span class="underline">General Provisions:</span> If any provision of this Agreement is held by a court of competent jurisdiction to be invalid or unenforceable, then such provision shall be enforced to the maximum extent permissible so as to affect the intent of this Agreement, and the remainder of this Agreement shall continue in full force and effect. The failure by either you or ASSURED PERFORMANCE to exercise or enforce any rights or provisions of this Agreement shall not constitute a waiver of such right or provision. You agree that any cause of action arising out of or related to the Service or this Agreement must commence within one (1) year after the cause of action arose; otherwise, such cause of action is permanently barred. This Agreement comprises the entire agreement between you and ASSURED PERFORMANCE and supersedes all prior agreements between the parties, regarding the subject matter contained herein. All provisions in this Agreement regarding representations and warranties, indemnification, disclaimers, payment obligations and limitations on liability shall survive any termination of this Agreement. We shall not be liable for loss or damage resulting from any cause beyond our reasonable control, including, but not limited to: (i) Internet network failures or Internet capacity limitations, or acts or omissions of any Internet Service Provider (ISP), telecommunications provider, or electrical utility (ii) compliance with regulations, orders or instructions of any federal, state or municipal government or any department or agent thereof that delay or restrict performance hereunder, or (iii) acts of God, acts or omissions of third parties.  Headings of particular Sections are inserted only for convenience and are not to be considered a part of this Agreement or be used to define, limit or construe the scope of any term or provision of this Agreement. Should any provision of this Agreement require judicial interpretation, the parties agree that the court or arbitrators construing the same shall not apply a presumption that the terms of this Agreement shall be more strictly construed against one party than against another.</p>
    <br/>
    <br/>
</div>